/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AchatsRouteImport } from './routes/achats'
import { Route as AdminAchatsRouteImport } from './routes/admin-achats'
import { Route as CalculateursRouteImport } from './routes/calculateurs'
import { Route as CasRouteImport } from './routes/cas'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonneesRouteImport } from './routes/donnees'
import { Route as ExamenRouteImport } from './routes/examen'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as ProRouteImport } from './routes/pro'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RevueRouteImport } from './routes/revue'
import { Route as SoutenirRouteImport } from './routes/soutenir'
import { Route as CasCaseIdRouteImport } from './routes/cas.$caseId'
import { Route as DemarcheIdRouteImport } from './routes/demarche.$id'
import { Route as LearnDeckIdRouteImport } from './routes/learn.$deckId'
import { Route as ParcoursDeckIdRouteImport } from './routes/parcours.$deckId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AchatsRoute = AchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAchatsRoute = AdminAchatsRouteImport.update({
  id: '/admin-achats',
  path: '/admin-achats',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculateursRoute = CalculateursRouteImport.update({
  id: '/calculateurs',
  path: '/calculateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const CasRoute = CasRouteImport.update({
  id: '/cas',
  path: '/cas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonneesRoute = DonneesRouteImport.update({
  id: '/donnees',
  path: '/donnees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenRoute = ExamenRouteImport.update({
  id: '/examen',
  path: '/examen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RevueRoute = RevueRouteImport.update({
  id: '/revue',
  path: '/revue',
  getParentRoute: () => rootRouteImport,
} as any)
const SoutenirRoute = SoutenirRouteImport.update({
  id: '/soutenir',
  path: '/soutenir',
  getParentRoute: () => rootRouteImport,
} as any)
const CasCaseIdRoute = CasCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasRoute,
} as any)
const DemarcheIdRoute = DemarcheIdRouteImport.update({
  id: '/demarche/$id',
  path: '/demarche/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnDeckIdRoute = LearnDeckIdRouteImport.update({
  id: '/learn/$deckId',
  path: '/learn/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursDeckIdRoute = ParcoursDeckIdRouteImport.update({
  id: '/$deckId',
  path: '/$deckId',
  getParentRoute: () => ParcoursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/achats': typeof AchatsRoute
  '/admin-achats': typeof AdminAchatsRoute
  '/calculateurs': typeof CalculateursRoute
  '/cas': typeof CasRouteWithChildren
  '/classement': typeof ClassementRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/donnees': typeof DonneesRoute
  '/examen': typeof ExamenRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/parcours': typeof ParcoursRouteWithChildren
  '/pro': typeof ProRoute
  '/profil': typeof ProfilRoute
  '/revue': typeof RevueRoute
  '/soutenir': typeof SoutenirRoute
  '/cas/$caseId': typeof CasCaseIdRoute
  '/demarche/$id': typeof DemarcheIdRoute
  '/learn/$deckId': typeof LearnDeckIdRoute
  '/parcours/$deckId': typeof ParcoursDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/achats': typeof AchatsRoute
  '/admin-achats': typeof AdminAchatsRoute
  '/calculateurs': typeof CalculateursRoute
  '/cas': typeof CasRouteWithChildren
  '/classement': typeof ClassementRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/donnees': typeof DonneesRoute
  '/examen': typeof ExamenRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/parcours': typeof ParcoursRouteWithChildren
  '/pro': typeof ProRoute
  '/profil': typeof ProfilRoute
  '/revue': typeof RevueRoute
  '/soutenir': typeof SoutenirRoute
  '/cas/$caseId': typeof CasCaseIdRoute
  '/demarche/$id': typeof DemarcheIdRoute
  '/learn/$deckId': typeof LearnDeckIdRoute
  '/parcours/$deckId': typeof ParcoursDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/achats': typeof AchatsRoute
  '/admin-achats': typeof AdminAchatsRoute
  '/calculateurs': typeof CalculateursRoute
  '/cas': typeof CasRouteWithChildren
  '/classement': typeof ClassementRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/donnees': typeof DonneesRoute
  '/examen': typeof ExamenRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/parcours': typeof ParcoursRouteWithChildren
  '/pro': typeof ProRoute
  '/profil': typeof ProfilRoute
  '/revue': typeof RevueRoute
  '/soutenir': typeof SoutenirRoute
  '/cas/$caseId': typeof CasCaseIdRoute
  '/demarche/$id': typeof DemarcheIdRoute
  '/learn/$deckId': typeof LearnDeckIdRoute
  '/parcours/$deckId': typeof ParcoursDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/achats'
    | '/admin-achats'
    | '/calculateurs'
    | '/cas'
    | '/classement'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/donnees'
    | '/examen'
    | '/import'
    | '/login'
    | '/parcours'
    | '/pro'
    | '/profil'
    | '/revue'
    | '/soutenir'
    | '/cas/$caseId'
    | '/demarche/$id'
    | '/learn/$deckId'
    | '/parcours/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/achats'
    | '/admin-achats'
    | '/calculateurs'
    | '/cas'
    | '/classement'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/donnees'
    | '/examen'
    | '/import'
    | '/login'
    | '/parcours'
    | '/pro'
    | '/profil'
    | '/revue'
    | '/soutenir'
    | '/cas/$caseId'
    | '/demarche/$id'
    | '/learn/$deckId'
    | '/parcours/$deckId'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/achats'
    | '/admin-achats'
    | '/calculateurs'
    | '/cas'
    | '/classement'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/donnees'
    | '/examen'
    | '/import'
    | '/login'
    | '/parcours'
    | '/pro'
    | '/profil'
    | '/revue'
    | '/soutenir'
    | '/cas/$caseId'
    | '/demarche/$id'
    | '/learn/$deckId'
    | '/parcours/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AchatsRoute: typeof AchatsRoute
  AdminAchatsRoute: typeof AdminAchatsRoute
  CalculateursRoute: typeof CalculateursRoute
  CasRoute: typeof CasRouteWithChildren
  ClassementRoute: typeof ClassementRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DonneesRoute: typeof DonneesRoute
  ExamenRoute: typeof ExamenRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  ParcoursRoute: typeof ParcoursRouteWithChildren
  ProRoute: typeof ProRoute
  ProfilRoute: typeof ProfilRoute
  RevueRoute: typeof RevueRoute
  SoutenirRoute: typeof SoutenirRoute
  DemarcheIdRoute: typeof DemarcheIdRoute
  LearnDeckIdRoute: typeof LearnDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achats': {
      id: '/achats'
      path: '/achats'
      fullPath: '/achats'
      preLoaderRoute: typeof AchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-achats': {
      id: '/admin-achats'
      path: '/admin-achats'
      fullPath: '/admin-achats'
      preLoaderRoute: typeof AdminAchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculateurs': {
      id: '/calculateurs'
      path: '/calculateurs'
      fullPath: '/calculateurs'
      preLoaderRoute: typeof CalculateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas': {
      id: '/cas'
      path: '/cas'
      fullPath: '/cas'
      preLoaderRoute: typeof CasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donnees': {
      id: '/donnees'
      path: '/donnees'
      fullPath: '/donnees'
      preLoaderRoute: typeof DonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examen': {
      id: '/examen'
      path: '/examen'
      fullPath: '/examen'
      preLoaderRoute: typeof ExamenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revue': {
      id: '/revue'
      path: '/revue'
      fullPath: '/revue'
      preLoaderRoute: typeof RevueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soutenir': {
      id: '/soutenir'
      path: '/soutenir'
      fullPath: '/soutenir'
      preLoaderRoute: typeof SoutenirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas/$caseId': {
      id: '/cas/$caseId'
      path: '/$caseId'
      fullPath: '/cas/$caseId'
      preLoaderRoute: typeof CasCaseIdRouteImport
      parentRoute: typeof CasRoute
    }
    '/demarche/$id': {
      id: '/demarche/$id'
      path: '/demarche/$id'
      fullPath: '/demarche/$id'
      preLoaderRoute: typeof DemarcheIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$deckId': {
      id: '/learn/$deckId'
      path: '/learn/$deckId'
      fullPath: '/learn/$deckId'
      preLoaderRoute: typeof LearnDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours/$deckId': {
      id: '/parcours/$deckId'
      path: '/$deckId'
      fullPath: '/parcours/$deckId'
      preLoaderRoute: typeof ParcoursDeckIdRouteImport
      parentRoute: typeof ParcoursRoute
    }
  }
}

interface CasRouteChildren {
  CasCaseIdRoute: typeof CasCaseIdRoute
}

const CasRouteChildren: CasRouteChildren = {
  CasCaseIdRoute: CasCaseIdRoute,
}

const CasRouteWithChildren = CasRoute._addFileChildren(CasRouteChildren)

interface ParcoursRouteChildren {
  ParcoursDeckIdRoute: typeof ParcoursDeckIdRoute
}

const ParcoursRouteChildren: ParcoursRouteChildren = {
  ParcoursDeckIdRoute: ParcoursDeckIdRoute,
}

const ParcoursRouteWithChildren = ParcoursRoute._addFileChildren(
  ParcoursRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AchatsRoute: AchatsRoute,
  AdminAchatsRoute: AdminAchatsRoute,
  CalculateursRoute: CalculateursRoute,
  CasRoute: CasRouteWithChildren,
  ClassementRoute: ClassementRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DonneesRoute: DonneesRoute,
  ExamenRoute: ExamenRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  ParcoursRoute: ParcoursRouteWithChildren,
  ProRoute: ProRoute,
  ProfilRoute: ProfilRoute,
  RevueRoute: RevueRoute,
  SoutenirRoute: SoutenirRoute,
  DemarcheIdRoute: DemarcheIdRoute,
  LearnDeckIdRoute: LearnDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
